version: 1
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
archives:
  - format: tar.gz
    name_template: '{{ .Binary }}_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip
changelog:
  sort: asc
  groups:
    - title: Breaking changes
      regexp: '^.*?[[:word:]](\([[:word:]]+\))??!:.+$'
      order: 0
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??:.+$'
      order: 1
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??:.+$'
      order: 2
    - title: "Documentations"
      regexp: '^.*?docs(\([[:word:]]+\))??:.+$'
      order: 3
    - title: "Styles"
      regexp: '^.*?style(\([[:word:]]+\))??:.+$'
      order: 4
    - title: "Code refactoring"
      regexp: '^.*?refactor(\([[:word:]]+\))??:.+$'
      order: 5
    - title: "Performance improvements"
      regexp: '^.*?perf(\([[:word:]]+\))??:.+$'
      order: 6
    - title: "Tests"
      regexp: '^.*?test(\([[:word:]]+\))??:.+$'
      order: 7
    - title: "Builds"
      regexp: '^.*?build(\([[:word:]]+\))??:.+$'
      order: 8
    - title: "Continuous integrations"
      regexp: '^.*?ci(\([[:word:]]+\))??:.+$'
      order: 9
    - title: "Chores"
      regexp: '^.*?chore(\([[:word:]]+\))??:.+$'
      order: 10
    - title: "Reverts"
      regexp: '^.*?revert(\([[:word:]]+\))??:.+$'
      order: 11
    - title: Others
      order: 999
